"""Generate PDF reports for NeuroDrishti AI MRI analyses."""

import io
import os
import tempfile
from datetime import datetime
from PIL import Image

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image as RLImage,
    Table,
    TableStyle,
    HRFlowable,
    KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.pdfgen import canvas


class NumberedCanvas(canvas.Canvas):
    """Canvas that computes total pages dynamically and adds running headers & footers."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#718096"))
        
        # Header rule and text
        self.drawString(40, 755, "BRAIN MRI AI ANALYSIS REPORT | EXPLAINABLE AI (Grad-CAM++)")
        self.drawRightString(612 - 40, 755, "RESEARCH & EDUCATIONAL USE ONLY")
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.75)
        self.line(40, 748, 612 - 40, 748)
        
        # Footer rule and text
        self.line(40, 48, 612 - 40, 48)
        self.drawString(40, 36, "CONFIDENTIAL - Generated by NeuroDrishti AI")
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(612 - 40, 36, page_str)
        self.restoreState()


def generate_pdf_report(
    filename: str,
    diagnosis_name: str,
    confidence: float,
    status_text: str,
    class_probabilities: dict,
    original_img_rgb,
    heatmap_img_rgb,
    overlay_img_rgb,
    tumor_info: dict,
    timestamp: str = None
) -> bytes:
    """
    Generate a dynamic, comprehensive PDF report and return as bytes.
    """
    if timestamp is None:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=40,
        rightMargin=40,
        topMargin=55,
        bottomMargin=55
    )

    styles = getSampleStyleSheet()

    # Custom typography styles
    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=18,
        leading=22,
        textColor=colors.HexColor("#1A365D"),
        spaceAfter=4
    )

    subtitle_style = ParagraphStyle(
        "DocSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#4A5568"),
        spaceAfter=12
    )

    section_heading = ParagraphStyle(
        "SectionHeading",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#2B6CB0"),
        spaceBefore=10,
        spaceAfter=6
    )

    body_style = ParagraphStyle(
        "ReportBody",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#2D3748")
    )

    bold_label = ParagraphStyle(
        "BoldLabel",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#1A202C")
    )

    disclaimer_style = ParagraphStyle(
        "DisclaimerStyle",
        parent=styles["Normal"],
        fontName="Helvetica-Oblique",
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#742A2A")
    )

    story = []

    # Title & Header
    story.append(Paragraph("BRAIN MRI AI ANALYSIS REPORT", title_style))
    story.append(Paragraph("Automated Diagnostic Assistance & Explainable AI Localization (Grad-CAM++)", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#3182CE"), spaceAfter=10))

    # 1. Analysis Information Table
    story.append(Paragraph("1. Analysis Information", section_heading))
    info_data = [
        [
            Paragraph("<b>Analysis Date/Time:</b>", bold_label),
            Paragraph(timestamp, body_style),
            Paragraph("<b>File Name:</b>", bold_label),
            Paragraph(filename, body_style)
        ],
        [
            Paragraph("<b>Model Architecture:</b>", bold_label),
            Paragraph("ResNet50 Transfer Learning", body_style),
            Paragraph("<b>Input Resolution:</b>", bold_label),
            Paragraph("224 × 224 pixels", body_style)
        ],
        [
            Paragraph("<b>Explainability Mode:</b>", bold_label),
            Paragraph("Grad-CAM++ (Higher-Order Gradients)", body_style),
            Paragraph("<b>Target Modality:</b>", bold_label),
            Paragraph("Brain MRI (Axial / T1 / T2)", body_style)
        ]
    ]

    info_table = Table(info_data, colWidths=[130, 135, 120, 145])
    info_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F7FAFC")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 10))

    # 2. AI Prediction Summary Table
    story.append(Paragraph("2. AI Diagnostic Prediction", section_heading))
    
    status_bg = colors.HexColor("#FFF5F5") if "Tumor Detected" in status_text else colors.HexColor("#F0FFF4")
    status_color = colors.HexColor("#C53030") if "Tumor Detected" in status_text else colors.HexColor("#22543D")

    pred_data = [
        [
            Paragraph("<b>Predicted Class:</b>", bold_label),
            Paragraph(f"<font size=11 color='#1A365D'><b>{diagnosis_name.upper()}</b></font>", body_style),
            Paragraph("<b>Confidence Score:</b>", bold_label),
            Paragraph(f"<font size=11 color='#2B6CB0'><b>{confidence:.2f}%</b></font>", body_style)
        ],
        [
            Paragraph("<b>Clinical Status:</b>", bold_label),
            Paragraph(f"<font color='{status_color}'><b>{status_text}</b></font>", body_style),
            Paragraph("<b>Action Required:</b>", bold_label),
            Paragraph("Clinical Specialist Review" if "Tumor" in status_text else "Routine Monitoring", body_style)
        ]
    ]

    pred_table = Table(pred_data, colWidths=[130, 135, 120, 145])
    pred_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), status_bg),
        ('GRID', (0, 0), (-1, -1), 0.75, colors.HexColor("#CBD5E0")),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(pred_table)
    story.append(Spacer(1, 10))

    # 3. Class Probabilities Breakdown
    story.append(Paragraph("3. Multi-Class Probability Distribution", section_heading))
    prob_headers = [
        Paragraph("<b>Class Name</b>", bold_label),
        Paragraph("<b>Softmax Probability</b>", bold_label),
        Paragraph("<b>Percentage</b>", bold_label),
        Paragraph("<b>Relative Assessment</b>", bold_label)
    ]
    
    prob_rows = [prob_headers]
    display_names = {
        "glioma": "Glioma",
        "meningioma": "Meningioma",
        "pituitary": "Pituitary Tumor",
        "notumor": "No Tumor Detected"
    }

    for k, v in class_probabilities.items():
        disp = display_names.get(k, k.capitalize())
        prob_val = float(v)
        is_primary = (disp.lower() == diagnosis_name.lower() or k == diagnosis_name.lower())
        assessment = "<b>Primary Diagnosis</b>" if is_primary else "Differential"
        row_bg = colors.HexColor("#EBF8FF") if is_primary else colors.white
        prob_rows.append([
            Paragraph(disp, body_style),
            Paragraph(f"{prob_val:.4f}", body_style),
            Paragraph(f"<b>{prob_val * 100:.2f}%</b>", body_style),
            Paragraph(assessment, body_style)
        ])

    prob_table = Table(prob_rows, colWidths=[150, 120, 110, 150])
    prob_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#EDF2F7")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E0")),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(prob_table)
    story.append(Spacer(1, 10))

    # 4. Explainable AI Visualizations
    story.append(Paragraph("4. Explainable AI (Grad-CAM++) Visualizations", section_heading))
    story.append(Paragraph(
        "Grad-CAM++ calculates higher-order partial derivatives (1st, 2nd, and 3rd order gradients) "
        "of the target class score with respect to feature maps of the final convolutional layer. "
        "Warm colors (red/yellow) indicate focal regions driving the neural network's decision.",
        body_style
    ))
    story.append(Spacer(1, 6))

    # Convert NumPy RGB images to temporary files for ReportLab embedding
    temp_files = []
    try:
        def save_temp_img(arr):
            fd, path = tempfile.mkstemp(suffix=".png")
            os.close(fd)
            Image.fromarray(arr).save(path, format="PNG")
            temp_files.append(path)
            return path

        orig_path = save_temp_img(original_img_rgb)
        heat_path = save_temp_img(heatmap_img_rgb)
        super_path = save_temp_img(overlay_img_rgb)

        img_w, img_h = 165, 165
        viz_data = [
            [
                RLImage(orig_path, width=img_w, height=img_h),
                RLImage(heat_path, width=img_w, height=img_h),
                RLImage(super_path, width=img_w, height=img_h)
            ],
            [
                Paragraph("<b>A: Original MRI Scan</b>", bold_label),
                Paragraph("<b>B: Grad-CAM++ Heatmap</b>", bold_label),
                Paragraph("<b>C: Explainable Overlay</b>", bold_label)
            ]
        ]
        viz_table = Table(viz_data, colWidths=[175, 175, 175])
        viz_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F7FAFC")),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ]))
        story.append(viz_table)

    finally:
        # Note: Do not delete temp files until doc.build completes
        pass

    story.append(Spacer(1, 10))

    # 5. Clinical Knowledge Base & Medical Context
    story.append(Paragraph("5. Clinical Knowledge & Reference Notes", section_heading))
    summary_data = [
        [
            Paragraph("<b>Condition:</b>", bold_label),
            Paragraph(tumor_info.get("name", diagnosis_name), body_style)
        ],
        [
            Paragraph("<b>Clinical Description:</b>", bold_label),
            Paragraph(tumor_info.get("details", "N/A"), body_style)
        ],
        [
            Paragraph("<b>Etiology / Risk Factors:</b>", bold_label),
            Paragraph(tumor_info.get("causes", "N/A"), body_style)
        ],
        [
            Paragraph("<b>Trusted Medical Resources:</b>", bold_label),
            Paragraph(tumor_info.get("resources", "N/A"), body_style)
        ]
    ]
    summary_table = Table(summary_data, colWidths=[140, 390])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F7FAFC")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 10))

    # 6. Important Medical Disclaimer
    story.append(Paragraph("6. Regulatory & Clinical Disclaimer", section_heading))
    disclaimer_box = [
        [
            Paragraph(
                "<b>MANDATORY NOTICE:</b> This AI-generated report is provided strictly for academic research, "
                "scientific evaluation, and clinical decision-support purposes. It DOES NOT replace a formal "
                "diagnostic evaluation by a licensed radiologist or neurologist. Definitive clinical management "
                "requires comprehensive clinical assessment, patient history, and multi-sequence MRI correlation.",
                disclaimer_style
            )
        ]
    ]
    disc_table = Table(disclaimer_box, colWidths=[530])
    disc_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#FFF5F5")),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#FEB2B2")),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(disc_table)

    # Build document with running headers/footers
    try:
        doc.build(story, canvasmaker=NumberedCanvas)
        pdf_bytes = buffer.getvalue()
    finally:
        buffer.close()
        for p in temp_files:
            if os.path.exists(p):
                try:
                    os.remove(p)
                except Exception:
                    pass

    return pdf_bytes
